all:
  hosts:
    node1:
      ansible_host: 158.160.164.140
      ip: 158.160.164.140
      access_ip: 158.160.164.140
    node2:
      ansible_host: 51.250.70.253
      ip: 51.250.70.253
      access_ip: 51.250.70.253
    node3:
      ansible_host: 89.169.163.63
      ip: 89.169.163.63
      access_ip: 89.169.163.63
    node4:
      ansible_host: 89.169.170.198
      ip: 89.169.170.198
      access_ip: 89.169.170.198
    node5:
      ansible_host: 130.193.52.15
      ip: 130.193.52.15
      access_ip: 130.193.52.15
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
