apiVersion: v1
kind: Service
metadata:
  name: kuliaev-diplom.ru
  namespace: kuliaev-diplom
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      nodeport: 30885
