apiVersion: v1
kind: Service
metadata:
  name: kuliaev-diplom-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - port: 80           
    targetPort: 80    
    nodePort: 30081  
