grafana:
  nodeSelector:
    app: grafana
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30080

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

