name: Docker Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_NAME: mkuliaev/my-nginx-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Dockerfile
        run: |
          ls -la my_app  # Проверка содержимого папки
          if [ ! -f "my_app/Dockerfile" ]; then
            echo "❌ Dockerfile not found in my_app directory!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: my_app  # Указываем папку с Dockerfile
          file: my_app/Dockerfile  # Явный путь
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          push: true

  deploy:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Update deployment image
        run: |
          kubectl set image deployment/kuliaev-diplom.ru \
            kuliaev-diplom-nginx=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            -n default
        env:
          REGISTRY: docker.io
          IMAGE_NAME: mkuliaev/my-nginx-app
