name: 'Terraform infrastructure'

on:
  push:
    branches: [main]
    paths: ['files/terraform/**']
  pull_request:
    branches: [main]
    paths: ['files/terraform/**']
  workflow_dispatch:
    inputs:
      apply:
        description: 'Type "true" to apply changes'
        required: true
        default: 'false'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    env:
      TF_VAR_token: ${{ secrets.YC_TOKEN }}
      TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_ssh_public: ${{ secrets.SSH_PUBLIC }}
     

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.8.0"

    - name: Terraform Init
      run: terraform -chdir=./files/terraform init

    - name: Terraform Format Check
      run: terraform -chdir=./files/terraform fmt -check

    - name: Terraform Validate
      run: terraform -chdir=./files/terraform validate

    - name: Terraform Plan
      run: terraform -chdir=./files/terraform plan -input=false -out=tfplan

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4 
      with:
        name: tfplan
        path: files/terraform/tfplan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true'
      run: terraform -chdir=./files/terraform apply -input=false tfplan
